// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.piirivalve.entities;

import java.lang.String;

privileged aspect Voimalik_alluvus_Roo_JavaBean {
    
    public String Voimalik_alluvus.getKommentaar() {
        return this.kommentaar;
    }
    
    public void Voimalik_alluvus.setKommentaar(String kommentaar) {
        this.kommentaar = kommentaar;
    }
    
}
